### ISSUE TITLE
Cannot read property 'statusCode' of null

### ISSUE THREAD

**Issue by Andreas890** [emsesp/EMS-ESP32#729]
After a recent update of the IOBroker Plugin to Version 1.15.0 and updating the EMS-ESP Hardware to Version v3.4.4 / Device Platform ESP32/ v4.4.2 the IOBROKER teh EMS-ESP plug in crashes frequently and the log file is containing a number of errors:
</html>
</body>

<body>
<html>

2022-11-06 15:22:24.943 - info: ems-esp.0 (2706) write change to ems-esp V3: ems-esp.0.boiler.heatingactivated: 0
--
**2022-11-06 15:22:25.058 - error: ems-esp.0 (2706) uncaught exception: Cannot read property 'statusCode' of null
2022-11-06 15:22:25.059 - error: ems-esp.0 (2706) TypeError: Cannot read property 'statusCode' of null**
at Request._callback (/opt/iobroker/node_modules/iobroker.ems-esp/lib/ems.js:556:45)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:400:28)
at Request. (/opt/iobroker/node_modules/request/request.js:1154:10)
at Request.emit (events.js:400:28)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:519:28)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
**2022-11-06 15:22:25.060 - error: ems-esp.0 (2706) Cannot read property 'statusCode' of null**
2022-11-06 15:22:25.064 - info: ems-esp.0 (2706) terminating
**2022-11-06 15:22:25.065 - warn: ems-esp.0 (2706) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-11-06 15:22:25.077 - error: ems-esp.0 (2706) uncaught exception: Cannot read property 'statusCode' of null
2022-11-06 15:22:25.078 - error: ems-esp.0 (2706) TypeError: Cannot read property 'statusCode' of null**
at Request._callback (/opt/iobroker/node_modules/iobroker.ems-esp/lib/ems.js:556:45)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:400:28)
at Request. (/opt/iobroker/node_modules/request/request.js:1154:10)
at Request.emit (events.js:400:28)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:519:28)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
**2022-11-06 15:22:25.078 - error: ems-esp.0 (2706) Cannot read property 'statusCode' of null
2022-11-06 15:22:25.628 - error: host.raspberrypiIO4 instance system.adapter.ems-esp.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-11-06 15:22:25.633 - info: host.raspberrypiIO4 Restart adapter system.adapter.ems-esp.0 because enabled**
2022-11-06 15:22:55.769 - info: host.raspberrypiIO4 instance system.adapter.ems-esp.0 started with pid 4172
2022-11-06 15:22:57.397 - info: ems-esp.0 (4172) starting. Version 1.15.0 in /opt/iobroker/node_modules/iobroker.ems-esp, node: v14.20.1, js-controller: 4.0.21
2022-11-06 15:22:57.581 - info: ems-esp.0 (4172) API version identified V3
2022-11-06 15:22:57.582 - info: ems-esp.0 (4172) start initializing ems states false

**Comment by proddy** [comment]
this is an issue with iobroker, not EMS-ESP. @tp1de can help you
